[colors.normal]
black = "#2E3440"
blue = "#5E81AC"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
yellow = "#EBCB8B"
white = "#D8DEE9"

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#46d9ff"
green = "#8FBCBB"
magenta = "#a9a1e1"
red = "#ff6c6b"
yellow = "#ecbe7b"
white = "#ECEFF4"

[colors.cursor]
cursor = "#81A1C1"
text = "CellBackground"

[colors.primary]
background = "#2E3440"
foreground = "#bbc2cf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000
