icons_format = "{icon}"

[theme]
theme = "nord-dark"
[theme.overrides]
idle_fg = "#81A1C1"

[icons]
icons = "awesome4"
[icons.overrides]
bat = [
    "| |",
    "|¼|",
    "|½|",
    "|¾|",
    "|X|",
]
bat_charging = " ^ "
cpu = ""

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:25) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = " $icon $utilization "
[[block.click]]
button = "left"
cmd = "kitty btop"

[[block]]
block = "memory"
format = " $icon  $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "custom"
command = "uname -r"
interval = "once"
format = "{} $text.pango-str() "

[[block]]
block = "notify"
format = " $icon {$paused{Off}|On} "
driver = "dunst"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "sound"
format = " $icon { $volume|} "
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
format = " $icon { $volume|} "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %R') "
