#! /bin/sh

# make sure sxhkd is running
pgrep -x sxhkd > /dev/null || sxhkd -c /home/fanatical/.config/sxhkd/sxhkdrc &

# fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

# set Keyboard Layout
setxkbmap -layout us


##########################
# bspwm color settings #
##########################

# Fore/background
foreground=#bbc2cf
background=#282c34

# black
color0=#1c1f24
color8=#3f444a

# red
color1=#ff6c6b
color9=#da8548

# green
color2=#98be65
color10=#4db5bd

# yellow
color3=#da8548
color11=#ecbe7b

# blue
color4=#51afef
color12=#2257A0

# magenta
color5=#c678dd
color13=#a9a1e1

# cyan
color6=#5699af
color14=#46d9ff

# white
color7=#202328
color15=#efefef


##########################
# bspwm general settings #
##########################

# set monitors
if xrandr -q | grep 'HDMI-1 connected'; then
xrandr --output DP-1 --off --output DP-2 --off --output DP-3 --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI-1 --mode 1680x1050 --pos 2560x561 --rotate normal
bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10
else
bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9 10
fi
xrandr --output DP-3 --mode 2560x1440

bspc config border_width 2
bspc config top_padding 2
bspc config right_padding 2
bspc config left_padding 2
bspc config bottom_padding 2
bspc config window_gap 4
bspc config top_monocle_padding 2
bspc config right_monocle_padding 2
bspc config left_monocle_padding 2
bspc config bottom_monocle_padding 2

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

# follow mouse focus
bspc config focus_follows_pointer true

# disable swapping workspaces on app launch
bspc config ignore_ewmh_focus true


################
# bspwm colors #
################

bspc config normal_border_color "$color0"
bspc config focused_border_color "$color14"
bspc config active_border_color "$color6"
bspc config urgent_border_color "$color1"
bspc config presel_border_color "$color3"
bspc config presel_feedback_color "$color12"


#############################
# assign Program Workspaces #
#############################

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# Firefox is uppercase on Debian/Ubuntu
# bspc rule -a Firefox desktop='^1' follow=off
# firefox is lowercase on Arch
# bspc rule -a firefox desktop='^1' follow=off
bspc rule -a steam desktop='^4' follow=off
bspc rule -a steamwebhelper desktop='^4' follow=off
bspc rule -a Lutris desktop='^2' follow=off
bspc rule -a virt-manager desktop='^4' follow=off
bspc rule -a Virt-manager desktop='^4' follow=off
bspc rule -a VirtualBox Manager desktop='^4' follow=off
bspc rule -a discord desktop='^6' follow=off


########################
# set apps to floating #
########################

# general applications that should be floating #
bspc rule -a About state=floating
bspc rule -a Gufw.py state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pulseeffects state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a copyq state=floating
bspc rule -a Yad state=floating
bspc rule -a nifskope.exe state=floating


################################
# Assign wineserver Workspaces #
################################

bspc rule -a steam_app_22380 desktop='^2' follow=off
bspc rule -a wow.exe desktop='^4' follow=off
bspc rule -a Overwatch.exe desktop='^4' follow=off
bspc rule -a battle.net.exe desktop='^4' follow=off
bspc rule -a nifskope.exe desktop='^4' follow=off


#######################
# custom startup apps #
#######################

# $HOME/.screenlayout/main-layout.sh &
xrandr --output DP-3 --set TearFree on --scale 0.9999x0.9999 &
xrandr --output DP-3 --scale 0.9999x0.9999 &
# polkit-dumb-agent &
# lxpolkit &
# xss-lock --transfer-sleep-lock -- $HOME/.config/i3/scripts/lock.sh &
picom &
udiskie &
numlockx &
polybar bspwm &
# polybar bspwm2 &
conky -c $HOME/.config/bspwm/apps/bspwm_conky.conf &
$HOME/.config/bspwm/scripts/xset-screen-blanking.sh &
$HOME/.config/bspwm/scripts/keyboard-settings.sh &
xsetroot -cursor_name left_ptr &
paplay $HOME/.config/bspwm/audio/windows-vista-startup.mp3 &
# redshift-gtk -l 47.7511:-120.7401 -t 5600:3400 &
nm-applet &
nitrogen --restore &
$HOME/.custom-exes/color-demo-app/cmdemo_script DP-3 1.3 &
copyq &
# kdeconnect-indicator &
steam &
firefox &
discord &

